version: '3.6'
services:
  app:
    image: cleydyr/tomcat7-jdk8_postgresql
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
    ports:
     - "8080:8080"
     - "8000:8000"
    volumes:
      - type: bind
        source: ./tomcat/Biblivre4.war
        target: /usr/local/tomcat/webapps/Biblivre4.war
    networks:
      - biblivre5
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: abracadabra
      POSTGRES_USER: postgres
    volumes:
      - type: bind
        source: ./postgres/pg_hba.conf
        target: /etc/postgresql/pg_hba.conf
      - type: bind
        source: ./postgres/postgresql.conf
        target: /etc/postgresql/postgresql.conf
      - type: bind
        source: ./postgres/create-database.sh
        target: /docker-entrypoint-initdb.d/create-database.sh
      - type: bind
        source: ./postgres/sql/createdatabase.sql
        target: /docker-entrypoint-initdb.d/sql/createdatabase.sql
      - type: bind
        source: ./postgres/sql/biblivre4.sql
        target: /docker-entrypoint-initdb.d/sql/biblivre4.sql
    ports:
      - "5432:5432"
    networks:
      biblivre5:
        aliases:
          - postgres

networks:
  biblivre5: